name: Publish 8.2-fpm-alpine

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.2/fpm-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.2-fpm-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
