name: Publish 7.4-cli-alpine

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          file: "dockerfile/7.4/cli-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:7.4-cli-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
