name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build_82_fpm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.2/fpm/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.2-fpm
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_82_fpm_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.2/fpm-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.2-fpm-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_82_cli:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.2/cli/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.2-cli
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_82_cli_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.2/cli-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.2-cli-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_81_fpm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/fpm/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.1-fpm
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_81_fpm_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/fpm-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.1-fpm-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_81_cli:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/cli/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.1-cli
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_81_cli_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/cli-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.1-cli-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_80_fpm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.0/fpm/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.0-fpm
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_80_fpm_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.0/fpm-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.0-fpm-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_80_cli:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.0/cli/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.0-cli
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

  build_80_cli_alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.0/cli-alpine/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/extended-php:8.0-cli-alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7

